### ISSUE TITLE
Can't boot successfully with Rock5b

### ISSUE THREAD

**Issue by DjofPlusPlus** [amazingfate/rk3588-live-iso#1]
Hello,

I'm writing here because I saw your post on the Rock 5 forum. My board is flashed with the latest EDK2 and can boot into Windows 11 from USB.

Sadly I can't get either of your ISOs to boot successfully from either USB or SD.
- Debian: I get the GRUB menu, but after selecting either Live System or safe mode, the screen flashes green, then the board reboots.
- Ubuntu: Boots to GRUB recovery console, can't see any filesystems on hd0, etc

I just thought I'd let you know. I'm no linux expert, but I can get you serial logs if you'd like.

**Comment by amazingfate** [comment]
It's better to have a dc power instead of a pd power because there is no pd support in edk2.

**Comment by DjofPlusPlus** [comment]
Well well! I was indeed using a DC 5V3A power source, but trying another one has indeed resolved the issue. Now I have Debian running from NVME. Thank you!
