### ISSUE TITLE
Can't  boot successfully form iscsi with OrangePI 5 Plus,Missing modules?

### ISSUE THREAD

**Issue by friend8179** [amazingfate/rk3588-live-iso#2]
I chosed the [debian-bookworm-live-arm64.hybrid.iso] IMG. I used the ventoy program to boot the whole iso and I installed it on iscsi by mounted the iscsi manually. The installation program is stuck in the last step--source-meida -u which means to unplug the installation media.  Everything seemed normal. The grub menu appeared.  It worked well and  loaded vmlinuz and initrd.img.

It finally stuck in the PCIe Link Fail
the screen displayed 

PCIe Link Fail
failed to initialize host

Gave up waiting for root file system device.Common Problems:
-Boot args(cat /proc/comdline)
-Missing modules

**Comment by amazingfate** [comment]
Can you boot from armbian? My iso uses common armbian's kernel for rk3588.

**Comment by friend8179** [comment]
> Can you boot from armbian? My iso uses common armbian's kernel for rk3588.

Armbian donsn't have any univers uefi iso so I donn't know how to test it. Is it possible that it is due to Airplane mode after the installtion?

**Comment by amazingfate** [comment]
Kernel can't find root partition so boot failed. It's not uefi related because kernel image and initramfs is already loaded by grub.
Maybe iscsi related kernel module is missing in initramfs.
