### ISSUE TITLE
Nanopc t6 

### ISSUE THREAD

**Issue by brightplastik** [amazingfate/rk3588-live-iso#3]
Greetings Liu, are you accustomed with this particular board?
I'd like to install your very developed images, but I don't seem to find a version that leads to an installation process. I installed a NOR with a copy of EDK2 (so UEFI), and every image I try to launch ends up with a black screen.
I might have overseen something stupid and I'm looking for some help.
Thank for your time!

**Comment by amazingfate** [comment]
I don't have nanopc t6, and haven't tested edk2 firmware for a longtime. I heard new version of edk2 firmware will load dtb from itself, but my iso need to load its own dtb. There should be an option in UEFI setting. The latest release iso should work with edk2 firmware v0.8.

**Comment by brightplastik** [comment]
Amazing Liu. That was just what I needed to be up and running. Version 0.8 of edk2 is simple enough to make every noob like me able to run your live iso. Installation was a breeze, and the gpu acceleration is magnificent. The nanopc t6 becomes a beast of optimization, with your debian. 
Now that I see it working, I can make the effort to understand how to make my SBC work with the bleeding edge versions of both your releases and  jiangcuo's UEFI proxmox release, perhaps.
Thank you a ton. Finding someone willing to help has been a challenge, till now. It's advanced stuff, and everyone is too busy, apparently. 
Thank you for making your amazing work accessible to the rising plethora of SBC owners.
I own you a glass of your preferred drink.

**Comment by brightplastik** [comment]
Hello Liu, another question please:

Do you know a reliable way to mount and modify the EFI partition?
It is by default mounted in `/boot/efi` by it is really stubborn and read-only.
I need to copy your DTBs in that folder, so to be able to execute an override, but I'm failing to mount, copy and paste, with the following method:

`root@proxmox:/home/gabo# mount -t vfat /dev/mmcblk0p1 /mnt/efi -o rw,umask=0000`

`root@proxmox:/home/gabo# ls /mnt/efi/dtb
base  overlays`

`root@proxmox:/home/gabo# cp -r /dtb/base/ /mnt/efi/dtb/base
cp: cannot stat '/mnt/efi/dtb/base': Input/output error`

`root@proxmox:/home/gabo# rm -rf /mnt/efi/dtb
rm: cannot remove '/mnt/efi/dtb/base': Read-only file system
rm: cannot remove '/mnt/efi/dtb/overlays': Read-only file system`

**Comment by amazingfate** [comment]
EFI partition is just a fat32 partition, and should get mounted with write permission.
EFI partition is created by ubuntu/debian installer, which should not have directory like `dtb`.
System installed by my iso will load dtb from /boot/dtb.
I just tested EDK2 V0.9.1 on h88k and I can install and boot ubuntu. Although EDK2 firmware has changed from `rk3588-hinlink-h88k.dtb` to `rk3588-hinlink-h88k`, grub will still load the correct dtb in /boot/dtb.
`Support DTB override & overlays` is disabled in uefi setting.
I just triggered a new iso building workflow. You can try it when build is done and see if new kernel/dtb from armbian will work.

**Comment by brightplastik** [comment]
Little feedback about `20240225-1731` that I didn't see coming:
![Screenshot from 2024-02-28 21-01-04](https://github.com/amazingfate/rk3588-live-iso/assets/45295288/4dbab0cc-8451-49db-b2c3-a0a68fcb29c9)
Hope this early report can be useful somehow...as this did not happen with `20230828-1127`

From [the log](http://paste.debian.net/hidden/e081964a/) The problem is the following:

```
...
E: Unable to locate package live-task-localisation
E: Unable to locate package live-task-recommended
...
```
So it is not your fault, I think.

**Comment by brightplastik** [comment]
@amazingfate 

I think the culprit is this:
`The repository 'https://deb.debian.org/debian bookworm-security Release' does not have a Release file.`

I was hoping 
```
sudo su
root@debian:/home/user# echo "deb http://deb.debian.org/debian-security/ bookworm-security contrib main non-free non-free-firmware" > /etc/apt/sources.list
```
would do the trick but it didn't...

**Comment by amazingfate** [comment]
You can try the latest iso with these two packages built in.

**Comment by brightplastik** [comment]
> You can try

I just did Liu. Thank you for the support! We (you!) acchieved a perfectly booting image on edk2!
So, success on the installation...
![Screenshot from 2024-03-01 18-28-24](https://github.com/amazingfate/rk3588-live-iso/assets/45295288/8fb942f1-6240-4005-9662-c57b90d9a49f)
...but there is still a minor problem with `--configure` command that was not present before.
```
dpkg: error processing package linux-image-legacy-rk35xx (--configure):
 installed linux-image-legacy-rk35xx package post-installation script subprocess returned error exit status 1
Setting up linux-dtb-legacy-rk35xx (24.2.1) ...
Armbian 'linux-dtb-legacy-rk35xx' for '5.10.160-legacy-rk35xx': 'postinst' starting.
Armbian: DTB: symlinking /boot/dtb to /boot/dtb-5.10.160-legacy-rk35xx...
'dtb' -> 'dtb-5.10.160-legacy-rk35xx'
Armbian 'linux-dtb-legacy-rk35xx' for '5.10.160-legacy-rk35xx': 'postinst' finishing.
Processing triggers for cracklib-runtime (2.9.6-5+b1) ...
Processing triggers for man-db (2.11.2-2) ...
Errors were encountered while processing: linux-image-legacy-rk35xx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Hope it can be useful.

EDIT:

maybe this is the culprit:
https://forum.armbian.com/topic/33266-errors-linux-image-legacy-rk35xxerrors

Will dig it.

**Comment by amazingfate** [comment]
What's the full output of command `sudo apt install linux-image-legacy-rk35xx linux-dtb-legacy-rk35xx --reinstall`?
Workflow is building a new iso with the latest 24.2.1 kernel, you can try it later.

**Comment by brightplastik** [comment]
> What's the full output of command `sudo apt install linux-image-legacy-rk35xx linux-dtb-legacy-rk35xx --reinstall`? 

```
root@proxmox:/home/gabo# apt install linux-image-legacy-rk35xx linux-dtb-legacy-rk35xx --reinstall
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 0 B/1.494 kB of archives.
After this operation, 0 B of additional disk space will be used.
E: Internal Error, No file name for linux-image-legacy-rk35xx:arm64

```
But I will try and install your [new iso](https://github.com/amazingfate/rk3588-live-iso/releases/download/20240302-0736/debian-bookworm-live-arm64.hybrid.iso) and see if the error is gone!

**Comment by amazingfate** [comment]
`sudo apt -f install`

**Comment by brightplastik** [comment]
> `sudo apt -f install`

Hey Liu, on a fresh install of your ISO this is what I get:
```
root@proxmox:/home/gabo# apt install linux-image-legacy-rk35xx linux-dtb-legacy-rk35xx --reinstall
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reinstallation of linux-image-legacy-rk35xx is not possible, it cannot be downloaded.
Reinstallation of linux-dtb-legacy-rk35xx is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@proxmox:/home/gabo# sudo apt -f install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Is it going to be a problem, working on this release?

**Comment by amazingfate** [comment]
You don't need to reinstall kernel packages because they are already installed.

**Comment by brightplastik** [comment]
> You don't need to reinstall kernel packages because they are already installed.

Sure enough...I was only recycling a command to see if the package is available.
As I told you, not having much knowledge means I frequently take shortcuts that are not the proper way to do things! (embarassed)
It seems to me the goal has been reached, anyway. 
Are you satisfied with the release? Can I help you debug anything else?

P.S: this shows up when updating apt:

> root@proxmox:/home/gabo# apt-get update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease                  
Hit:4 http://deb.debian.org/debian bookworm-backports InRelease                
Get:5 https://download.opensuse.org/repositories/home:/amazingfate:/panfork-mesa/Debian_12 ./ InRelease [1.918 B]
Ign:6 https://stpete-mirror.armbian.com/apt bookworm InRelease                 
Err:7 https://k-space.ee.armbian.com/apt bookworm Release
  404  Not Found [IP: 2001:bb8:4008:20:193:40:103:61 443]
Reading package lists... Done
E: The repository 'https://apt.armbian.com bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by amazingfate** [comment]
armbian repo mirror is broken with your network. You may try it serval days later.

**Comment by brightplastik** [comment]
> armbian repo mirror is broken with your network. You may try it serval days later.

Indeed!

```
gabo@proxmox:~$ sudo apt update
[sudo] password for gabo: 
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48,0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55,4 kB]        
Get:4 http://deb.debian.org/debian bookworm-backports InRelease [56,5 kB]      
Get:5 https://download.opensuse.org/repositories/home:/amazingfate:/panfork-mesa/Debian_12 ./ InRelease [1.918 B]
Get:6 https://fi.mirror.armbian.de/apt bookworm InRelease [53,3 kB]            
Get:7 http://deb.debian.org/debian bookworm-backports/main Sources.diff/Index [63,3 kB]
Get:8 http://deb.debian.org/debian bookworm-backports/main arm64 Packages.diff/Index [63,3 kB]
Get:9 http://deb.debian.org/debian bookworm-backports/main all Contents (deb).diff/Index [63,6 kB]
Get:10 http://deb.debian.org/debian bookworm-backports/main Sources T-2024-03-03-0807.13-F-2024-03-02-2007.43.pdiff [1.824 B]
Get:11 http://deb.debian.org/debian bookworm-backports/main arm64 Packages T-2024-03-03-0807.13-F-2024-03-03-0208.18.pdiff [698 B]
Get:10 http://deb.debian.org/debian bookworm-backports/main Sources T-2024-03-03-0807.13-F-2024-03-02-2007.43.pdiff [1.824 B]
Get:11 http://deb.debian.org/debian bookworm-backports/main arm64 Packages T-2024-03-03-0807.13-F-2024-03-03-0208.18.pdiff [698 B]
Get:12 http://deb.debian.org/debian bookworm-backports/main all Contents (deb) T-2024-03-03-0807.13-F-2024-03-03-0208.18.pdiff [599 B]
Get:12 http://deb.debian.org/debian bookworm-backports/main all Contents (deb) T-2024-03-03-0807.13-F-2024-03-03-0208.18.pdiff [599 B]
Get:13 https://fi.mirror.armbian.de/apt bookworm/main arm64 Packages [169 kB]
Get:14 https://fi.mirror.armbian.de/apt bookworm/main all Packages [4.815 B]
Get:15 https://fi.mirror.armbian.de/apt bookworm/main all Contents (deb) [31,7 kB]
Get:16 https://fi.mirror.armbian.de/apt bookworm/main arm64 Contents (deb) [5.030 kB]
Get:17 https://fi.mirror.armbian.de/apt bookworm/bookworm-utils arm64 Packages [13,3 kB]
Get:18 https://fi.mirror.armbian.de/apt bookworm/bookworm-utils all Packages [2.207 B]
Get:19 https://fi.mirror.armbian.de/apt bookworm/bookworm-utils arm64 Contents (deb) [15,7 kB]
Get:20 https://fi.mirror.armbian.de/apt bookworm/bookworm-utils all Contents (deb) [6.547 B]
Get:21 https://fi.mirror.armbian.de/apt bookworm/bookworm-desktop arm64 Packages [2.673 B]
Get:22 https://fi.mirror.armbian.de/apt bookworm/bookworm-desktop all Packages [982 B]
Get:23 https://fi.mirror.armbian.de/apt bookworm/bookworm-desktop arm64 Contents (deb) [15,6 kB]
Get:24 https://fi.mirror.armbian.de/apt bookworm/bookworm-desktop all Contents (deb) [385 B]
Fetched 5.701 kB in 5s (1.219 kB/s)           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

``` 

You are very clever, Liu!
