### ISSUE TITLE
ubuntu password

### ISSUE THREAD

**Issue by E1t2han** [amazingfate/rk3588-live-iso#4]
- hi Liu, the first time I boot the system from the usb, what is the password?
![IMG_20240613_230024](https://github.com/amazingfate/rk3588-live-iso/assets/125975503/499ae942-d751-45c1-8ca1-5c69564defd2)

**Comment by amazingfate** [comment]
This iso is built by debian-live, so the default user/password is the same: `user / live`.

**Comment by E1t2han** [comment]
thank you

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
