### ISSUE TITLE
Missing partition table in ISO

### ISSUE THREAD

**Issue by musicBoxes** [amazingfate/rk3588-live-iso#5]
Following the recommended supported OS on [edk2-rk3588](https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#supported-oses), I downloaded the latest version of iso (tag 20240302-0736). However, the balenaEther shows that the iso is missing the partition table. I tried both Debian and Ubuntu but got the same warning. Then I ignored the warning and flash the SD card with the iso. However, neither one can boot on my ROCK 5 ITX.

![fig](https://github.com/user-attachments/assets/1777f762-543f-4522-a2c0-3706209a0dd2)

**Comment by tehbra1n** [comment]
what was the solution here?

**Comment by amazingfate** [comment]
> what was the solution here?
> 

this is an iso, which has no differences on booting with official isos from linux distros like debian/ubuntu/fedora. I have never heard that someone is booting an sd card flashed with an iso on an arm SBC. It's better to boot it from a udisk formatted by ventoy.
